apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  namespace: sayk
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      volumes:
        - name: nginx-data
          persistentVolumeClaim:
            claimName: nginx-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: sayk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
